version: "3.9"
services:
    mariadb:
        container_name: mongo-nodejs
        image: mongo
        # ports:
        #     - 3307:3306
        environment:
        - MONGO_INITDB_DATABASE=node-ecom
        # - MONGO_INITDB_ROOT_USERNAME=admin
        # - MONGO_INITDB_ROOT_PASSWORD=admin
        # ports:
        # - '27017-27019:27017-27019'

        networks:
            - webnet-nodejs

    redis:
        container_name: redis-nodejs
        image: redis:6.2
        networks:
            - webnet-nodejs

networks:
    webnet-nodejs:
        name: webnet-nodejs
        driver: bridge
