@url=http://localhost:3000/v1/api
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRmYjA3OTA4YTcwMjc2NTdjYjgyN2VmIiwiZW1haWwiOiJzaG9wYmVuOUBlbWFpbC5jb20iLCJpYXQiOjE2OTU0Mzc3MjEsImV4cCI6MTY5NTUyNDEyMX0.q4t4xKawR-2CjjPPOR1HpzuLZk9uQXePClcj0A3egrIDujmdMa8n9lCIPm-8_iND1u3azgloGP82ERvEG_GvIZrAzFqxLxusa4LaujUlAvIzBAqNFT99sm0oBxO09yIukCzdhJ8tO6vt-rD7rVoO4E87AhYEwddfkG9rM5iybnLJ7041d0wVhYJax5BkKdo5unfTBja5wqihbQn-DvuMLPRu8lZ4oh44o3lrEnBmWoKEmOC4STDpJ3AywsCb3zPmpuOJ9tVeU4oiXY7bRjhZ2pIoCggQYFUqElJdrVyngvj4Cb5XlurgN9dnmYWGNRiH54851Wu30yjDZwhRDgNcCiqdHbSQUE9X9mDhkIgh9BejfZc8NaaI8cf3S6h6h8WC29yjmSbdWZ64HtO6_OwG__M7Q1_YTV3UZrYI1-Z6QdSUvJ43g_VNA-7gX93cIXPo7mBv498z7pUia9VD9o4RGqJ7OQaL16xzW0JZR1p5yjQamtFCcntdKQmA-kwiHR_WWbsPYDnKaGYZ8SVDcjGSHDeH7SckE-YSoK3cXObrRoPkawOVEWkNM2SSCMFnNA2QnORNu_PJTJvFY-ZIG9eosODW4v5BAvZ_Z2MpoKGcB_120rYWiP0xNLtM010hx6w4cthkp_1FsBGdcRozcoY_1RcjodraxXwi8fdkSrUlzJ4
### signup
POST {{url}}/signup
Content-Type: application/json

{
    "name":"Shop Ben",
    "email":"shopben9@email.com",
    "password":"benthunder@123"
}

### signin
POST {{url}}/signin
Content-Type: application/json

{
    "email":"shopben9@email.com",
    "password":"benthunder@123"
}

### logout
POST {{url}}/logout
Content-Type: application/json
x-client-id: 64fb07908a7027657cb827ef
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRmYjA3OTA4YTcwMjc2NTdjYjgyN2VmIiwiZW1haWwiOiJzaG9wYmVuOUBlbWFpbC5jb20iLCJpYXQiOjE2OTQyMDEyMzcsImV4cCI6MTY5NDI4NzYzN30.A6IJ4xuaTZAMqYbE-NxRqMGYP_2iCM3MLDacT1SQiOUZ5U6nzmSOKVGNfCETXIhpdWirMvVjC7uVyG-osD_fqsKc0fsybb6baYUGlxPzLGVwVQ3Bb4uKS7h-mvVksNX8w2qBQXRCYIfYGKzEULi0A7XVJzlb7N1qzJ6ixKve9mOB5sBRV3Ll-pJr1JwZf7T0rZrKFwjdmCJES1LXuaGTEU6uY9S3WhXLILr68F5J5fGzKAyHD0EVBuzwnX-fp3c6Wjzo5a3fxAnkHPNmDvP-JpeVzitc5klyEBGbiPNMLm91bmy6qBIS6QWCidLs0iEr1l-Ohd7cru6uvsJsCs4G7Bx1uJJCZOAlv5SmpYcGNtqBSi21fm-KbD7RPXNAubx9X-spPo3GCoT8YbBDdzhAgQFI_cLOZDHH50wz21WFH30d7dyedyMI4o932DVkvSLGqRZ8E-xlCX9M75_TIaC71shV00yg-KoTeXgvX4lPZ9PzQSR-di6k8iUrVc7dmGahCgTSCxi0fZJXXHnenNEgpI0jnjT3pRln0JPbbXrRVKTWveUOGr7OSb8qtXW_Dma332xQzbSESzOELN4CfcE9p9qgh7IRBjaZYHSvGkWHvgnK7uQxt0TVoABm2bfQ6BNuLwo4Hco6D7q1zIfVN-7sZL2T76awmgKdq66kuCxubLY

### refresh token
POST {{url}}/refresh_token
Content-Type: application/json
x-client-id: 64fb07908a7027657cb827ef
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRmYjA3OTA4YTcwMjc2NTdjYjgyN2VmIiwiZW1haWwiOiJzaG9wYmVuOUBlbWFpbC5jb20iLCJpc19yZWZyZXNoIjp0cnVlLCJpYXQiOjE2OTQyMDIwOTMsImV4cCI6MTY5NDgwNjg5M30.An7MTpiWI04mye84Cy1virY1fbMgbHqY9PWfXMAZPUvvRWUvIs5OJp-6vaXbK4QeoHVYiDg1ZCbiUh2CuXSzFL3tv2qE5SxkVX_-MxjcEk6OoR3C8tnc2csgkzQhBoOaxtD1IVMrAYN_jdCTb3BYOOasE08kKbqRQ4M5MzQ-VlPK835SzfEgSeJ-x8pqAKr_NkzTfxfkvGy8Mmc3DXu9AIekHeVnA19xaEMtSAziPcPHqBg6SrK2thZcSBrYyTjo9OI_bMNlADY4UokJi6mf0riaAGpTmDC-v9e8qZ7IjUn4OjZTWPTo5hUC2xaykS_v32OluKaKLEAxVLTbYJwhrzLNJs3gq_Vy9wpTEk-mUuhw9t493B0VYKiRa4UGsD18xCZlAknhtgeys3591YOED8xCVnl0ReDXOj1cZ4ulDMV5w8w_q5w6RJlOfhVY1EXwnE62jd4KZ83ezGNZtwrJaEU-j_StiPFi7wL113mzjBZq8MRGcpwHwpRQlgT7gl9AtL42dOMXDI-BnBsEJdCG-z4_VSH7mfPIggbtS0w5YQpX5D4ok2MEKgKUhkVtLKuhlBnqUiXY_xO4VSGbG_o5F43ZGcu6NuecM-pIy5HRgO_kpfeAbz4-6TpUp0rzicrRwBayn0zqJXzC7sXzuPE4JN-Q4XBCOUTdaLKgbYcpub0

### create new product
POST {{url}}/product
Content-Type: application/json
x-client-id: 64fb07908a7027657cb827ef
Authorization: {{token}}

{
    "product_name": "New jeans 5",
    "product_type": "Clothing",
    "product_description": "Hello New jeans",
    "product_price": 29.9,
    "product_user": "64fb07908a7027657cb827ef",
    "product_thumb": "no_image",
    "product_quanity": 100,
    "product_attributes": {
        "brand": "Ben",
        "size": "XL",
        "material": "Jean"
    }
}